### ISSUE TITLE
Features of both the datasets

### ISSUE THREAD

**Issue by lucky-23** [Run542968/GAP#1]
Hello, thanks for your wonderful work. I would like to know if you could share the features in google drive? I am having some trouble accessing the features through the given link.

**Comment by Run542968** [comment]
ok, I'll try it and share you the link with you later.

**Comment by Run542968** [comment]
ok, I'll try it and share the link with you later.

**Comment by lucky-23** [comment]
Thank you. Looking forward to it!

**Comment by Run542968** [comment]
Hi, You can try downloading from this [link](https://drive.google.com/file/d/191hnyqHsDQjmDIYPqEQ8J62MpEGZEmJw/view?usp=sharing), please let me know if there are any other issues.

**Comment by lucky-23** [comment]
Hi, there are no issues. Thank you very much :)
